CREATE TABLE utilisateur (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    mot_de_passe VARCHAR(255) NOT NULL,
    type_compte ENUM('CLIENT', 'ORGANISATEUR') NOT NULL,
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
