package com.project.entity.utilisateur;

import java.sql.Timestamp;

/**
 * Represents a user in the system.
 * Can be a client or an organizer.
 */
public class Utilisateur {
    private int id;
    private String nom;
    private String email;
    private String motDePasse;
    private String typeCompte; // 'CLIENT' ou 'ORGANISATEUR'
    private Timestamp dateCreation;

    /**
     * Default constructor.
     */
    public Utilisateur() {
    }

    /**
     * Constructor with main fields.
     * ID is usually auto-generated by the database.
     * 
     * @param nom        Name of the user.
     * @param email      Email address.
     * @param motDePasse Password.
     * @param typeCompte Account type ('CLIENT' or 'ORGANISATEUR').
     */
    public Utilisateur(String nom, String email, String motDePasse, String typeCompte) {
        this.nom = nom;
        this.email = email;
        this.motDePasse = motDePasse;
        this.typeCompte = typeCompte;
    }

    /**
     * Returns the user ID.
     * 
     * @return The user ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the user's name.
     * 
     * @return The name.
     */
    public String getNom() {
        return nom;
    }

    /**
     * Returns the user's email.
     * 
     * @return The email address.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Returns the password.
     * 
     * @return The password.
     */
    public String getMotDePasse() {
        return motDePasse;
    }

    /**
     * Returns the account type.
     * 
     * @return The account type (e.g., 'CLIENT').
     */
    public String getTypeCompte() {
        return typeCompte;
    }

    /**
     * Returns the account creation date.
     * 
     * @return The creation timestamp.
     */
    public Timestamp getDateCreation() {
        return dateCreation;
    }

    /**
     * Sets the user ID.
     * 
     * @param id The new ID.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Sets the user's name.
     * 
     * @param nom The new name.
     */
    public void setNom(String nom) {
        this.nom = nom;
    }

    /**
     * Sets the user's email.
     * 
     * @param email The new email address.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Sets the password.
     * 
     * @param motDePasse The new password.
     */
    public void setMotDePasse(String motDePasse) {
        this.motDePasse = motDePasse;
    }

    /**
     * Sets the account type.
     * 
     * @param typeCompte The new account type.
     */
    public void setTypeCompte(String typeCompte) {
        this.typeCompte = typeCompte;
    }

    /**
     * Sets the creation date.
     * 
     * @param dateCreation The new creation timestamp.
     */
    public void setDateCreation(Timestamp dateCreation) {
        this.dateCreation = dateCreation;
    }

    /**
     * Returns a string representation of the user.
     * 
     * @return A string containing user details.
     */
    @Override
    public String toString() {
        return "Utilisateur{" +
                "id=" + id +
                ", nom='" + nom + '\'' +
                ", email='" + email + '\'' +
                ", motDePasse='" + motDePasse + '\'' +
                ", typeCompte='" + typeCompte + '\'' +
                ", dateCreation=" + dateCreation +
                '}';
    }
}
